# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 Mohamed Hammad & Spacecraft Software

[package]
name = "aetheric-stratum"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
crop = { workspace = true }
arc-swap = { workspace = true }
dashmap = { workspace = true }
aetheric-ipc-types = { path = "../aetheric-ipc-types" }

[dev-dependencies]
criterion = { workspace = true }
proptest = { workspace = true }

[lints]
workspace = true
